/**
 **************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 **************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 **************************
 */

#if !defined(_SOFT_FP) && defined(_ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "stm32f103x6.h"
#include "core_cm3.h"
#include "Scheduler.h"
#include "Stm32_F103C8_TIM_Driver.h"



void clock_init(void)
{

	//Enable clock to AFIO
	AFIO_GPIO_CLK_EN();
	//Enable clock to port A
	RCC_GPIOA_CLK_EN();
	//Enable clock to port B
	RCC_GPIOB_CLK_EN();


}


int main(void)
{
	clock_init();


	TIM_Config_t timer_config ;


	timer_config.TIM_Mode =  TIM_Mode_PWM;
	//timer_config.PWM.Channel = TIM_CHANNEL_4;
	timer_config.PWM.Ouptut_On_Compare_Match = PWM_Compare_Match_High;
	timer_config.PWM.Mode = PWM_Mode_EDGE_DOWN;
	timer_config.PWM.Compare_value = 45000;
	timer_config.Prescaler = 8 ;
	timer_config.Auto_Reload_Value = 60000 ;
	timer_config.IRQ_Enable = TIM_IRQ_MODE_None;
	timer_config.P_IRQ_CallBack = NULL ;

	MCAL_TIM_GPIO_Set_Pins(TIM3, TIM_CHANNEL_1, TIM_Mode_PWM);
	MCAL_TIM_GPIO_Set_Pins(TIM3, TIM_CHANNEL_2, TIM_Mode_PWM);
	MCAL_TIM_GPIO_Set_Pins(TIM3, TIM_CHANNEL_3, TIM_Mode_PWM);
	MCAL_TIM_GPIO_Set_Pins(TIM3, TIM_CHANNEL_4, TIM_Mode_PWM);


	timer_config.PWM.Channel = TIM_CHANNEL_1;
	MCAL_TIM_Init(TIM3,&timer_config );

	timer_config.PWM.Channel = TIM_CHANNEL_2;
	MCAL_TIM_Init(TIM3,&timer_config );

	timer_config.PWM.Compare_value = 15000;
	timer_config.Auto_Reload_Value = 60000 ;
	timer_config.PWM.Channel = TIM_CHANNEL_3;
	MCAL_TIM_Init(TIM3,&timer_config );

	timer_config.PWM.Channel = TIM_CHANNEL_4;
	MCAL_TIM_Init(TIM3,&timer_config );


	MCAL_TIM_Start(TIM3);

	while (1)
	{

	}

}
