/**
 ****
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ****
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ****
 */

#if !defined(_SOFT_FP) && defined(_ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"
#include "stm32f103x6.h"
#include "core_cm3.h"
#include "Scheduler.h"
#include "Stm32_F103C8_TIM_Driver.h"
#include "Stm32f103c6_ADC.h"
#include "Stm32_F103C8_WWDG_Driver.h"
#include "Delay.h"



void clock_init(void)
{

	//Enable clock to AFIO
	AFIO_GPIO_CLK_EN();
	//Enable clock to port A
	RCC_GPIOA_CLK_EN();
	//Enable clock to port B
	RCC_GPIOB_CLK_EN();



}


int main(void)
{



	clock_init();
	HAL_Delay_Init();

	WWDG_Config_t WWDG_Config ;

	WWDG_Config.Prescaler = WWDG_Counter_div_2;
	WWDG_Config.Counter_Start_VAL = 83 ;
	WWDG_Config.Window_Value = 80 ;
	WWDG_Config.EWI_IRQ_Enable = WWDG_EWI_IRQ_None ;
	WWDG_Config.P_IRQ_CallBack = NULL ;

    MCAL_WWDG_Init(&WWDG_Config);




	while (1)
	{

		MCAL_WWDG_Start();

        Delay_ms(10);

		MCAL_WWDG_Kick();

	}

}
